### ISSUE TITLE
Few bugs.

### ISSUE THREAD

**Issue by TaiDak** [Goldenfreddy0703/plugin.video.kaito.beta#23]
Just a few bugs that I've seen as of beta 18

- next up menu is broken in all the betas, as far as I've tested. 
It gets populated, but there's an error if you try to play an episode. Original kaito 11 works.
- fanart doesn't work for some anime if you have title  language set to romaji, English appears to work better.
- If have title language set to English, and an anime in your list that doesn't have an English name equivalent, your list won't open and will just give an error. Title language set to romaji works good though.

Those three are the only major issues I've encountered so far, although I can get somewhat around them.

**Comment by jkaw** [comment]
I’ll take a look at this stuff eventually. 

when I do get to it eventually, can you provide examples of anime for each issue?

**Comment by jkaw** [comment]
@TaiDak Can you provide examples for issues 2 and 3? I have a solution for number 1 already, but am waiting to push it until I can look at the other issues.

**Comment by TaiDak** [comment]
Ok, so I got confused, fanart does work for anime in romaji pretty good, I don't know why it wasn't working good before

Issue 3 only affects AniList watchlists. If you have title language set to English in the add-on settings, your watchlist might not open if you have some specific anime in your list. I thought it was because they had no English title equivalent, but I don't think that's the case anymore. I went through my entire list and these anime specifically create an error that doesn't let you open your watchlist

- Tonari no kaibutsu-kun: Tonari no Gokudou-kun
- Mayo Chiki
- High School DxD
- Girls Bravo: Second Season
- Eureka 7 AO
- Digimon Frontier
- Digimon Tamers
-Digimon Evolution
-Deadman Wonderland
- Toaru Kagaku no Railgun: Misaka-san was Ima Chuumoku no mato Desukara
-Charlotte
-Iketeru Futari
-Dagashi Kashi

If I set title language to romaji, the watchlists open normally. 
https://paste.kodi.tv/ipibotutef
My log

**Comment by jkaw** [comment]
@TaiDak 

So to summarize:
Issue 1 should have been fixed in #25 
Issue 2 seems to not be an issue anymore
Issue 3 should be fixed in #26 

You should be able to test Issue 1 in the current beta. 
Issue 3 will be testable whenever #26 is merged and a release is made.
Please let me know if these issues are fixed for you so I can close this.

**Comment by TaiDak** [comment]
Tested your commit, it works perfectly
