### ISSUE TITLE
Crashes to main screen on shield 

### ISSUE THREAD

**Issue by Liquidrag** [Goldenfreddy0703/plugin.video.kaito.beta#27]
Kodi crashes on the shield if you have a widget pointing to kaito beta. Removing the widget seems to stop the crashing. 

lates shield os (not beta)
Kodi 19.4
Latest Arctic horizon 

Thank you for updating kaito. I’m happy to have watched indicators back in my list.

**Comment by Goldenfreddy0703** [comment]
Can you send me a log? The crashing doesn't happen to me when I make Kaito beta widgets.

**Comment by Liquidrag** [comment]
Seems to be working fine now. It must’ve been a corrupt file during install so a delete and reinstall did the trick.

**Comment by Goldenfreddy0703** [comment]
That's good and incase you run into anymore problems, Do the troubleshooting steps in my pinned comment and that should help you tremendously.
