### ISSUE TITLE
Skip Intro Dialog and Playing Next Dialog

### ISSUE THREAD

**Issue by MAR2196** [Goldenfreddy0703/plugin.video.kaito.beta#28]
When attempting to use either Skip Intro or Playing Next Dialog options, the prompt will show up at the right time of the episode but will not function when interacted with. Attached is a pic of the issue I am having. The Playing Next prompt is frozen and I am unable to interact with anything without closing it.
![Next Up](https://user-images.githubusercontent.com/106176223/170091776-30423727-75c7-4dce-84cc-831282ab908e.png)

Let me know if this is just an issue on my end, thank you for all of the hard work!

**Comment by jkaw** [comment]
Can you provide names of the shows this happens to you on?

**Comment by MAR2196** [comment]
I just tried it with a few shows on a fresh install. Issue is present on both my desktop and firetv.
Shingeki no Kyojin
Monster
Bleach

**Comment by Goldenfreddy0703** [comment]
Hey so im sorry for not responding to this but i had this problem in the past before and it was due to the skin i was using, what skin are you using @MAR2196?

**Comment by Goldenfreddy0703** [comment]
Did you also try the troubleshooting steps?

**Comment by MAR2196** [comment]
I just ran thru the troubleshooting steps. No luck. What skin are you using?

**Comment by Goldenfreddy0703** [comment]
Auramod, I seen this happen once and idk why it's glitching for you. Ok what I would do is wipe the app data and try to configure everything again and try again. Or try reinstalling the addon and if that doesn't work then I may have to have to try it tomorrow and see why it's happening

**Comment by jkaw** [comment]
This is happening to me pretty consistently on arctic horizon. I'll take a look.

**Comment by Goldenfreddy0703** [comment]
Oh, ok that's odd but I might have a way to fix that tommawow.

**Comment by jkaw** [comment]
@MAR2196 
This should be fixed in #31 whenever it gets released. This was basically an incomplete feature. I figured out where to get the data, but I didn't like how big and how transparent it was and I ended up just copying the playing next window from Seren. This was originally based off it after all.

**Comment by MAR2196** [comment]
It is working great, thanks for the fix!
