### ISSUE TITLE
Mark As watched not working

### ISSUE THREAD

**Issue by MAR2196** [Goldenfreddy0703/plugin.video.kaito.beta#29]
Hello, when attempting to mark an episode as watched, the screen will load for a bit but will not actually mark the episode as completed. This wasn't an issue in the previous versions of Kaito prior to 0.0.11. For the record, I do not use any watchlists such as mal.  Attached is a video of the issue.

https://user-images.githubusercontent.com/106176223/170093131-16d3bb18-4c37-4d4f-851c-d173fd3bb6d4.mp4

Let me know if there's anyone else having this issue as well. Thank you for the hard work, I appreciate it!!

**Comment by MAR2196** [comment]
I just ran a fresh install. I had the correct context menus in both cases. Source select works fine but not mark as watched. Tested on both my desktop and fire tv.

**Comment by jkaw** [comment]
Ok, so I remember I never fixed that, only the select sources thing. 
I think it would take a while to fix this mark as watched issue.
SwagOtaku changes all of the paths of the urls for almost every action, and now the regular kodi database is having a hard time relating a play count with the new paths.
I'll take a look, but in the meantime, you may want to just try to use one of the integrated watchlists...

**Comment by jkaw** [comment]
There is an option to use the old kaito menus actually that I recently implemented. You can access them through Settings/General. 
At the bottom there is a Use Kaito 10 Menus option. You will have to do a rebuild database after.

However, I just checked and the mark as watched function is working there. I reimplemented those menus due to speed issues on slower devices, so some fanart and episode images may not work, but the episode info should all work.

**Comment by MAR2196** [comment]
Great, thank you for looking into it! I'll most likely switch to using an integrated watchlist, I just figured I'd post the issue here to keep track of it. Thanks for all of your efforts, I appreciate it!!

**Comment by jkaw** [comment]
I just made a pull request that will fix this if you don't have the Watchlist Update setting enabled. 
I just assume if you have an integrated watchlist you wouldn't want a watchlist that can't be synced to your devices anyway. 
I'm open to creating a whole new setting for it though.

**Comment by jkaw** [comment]
Also, it turns out it wasn't the changed paths from SwagOtaku that broke it, but rather the new list builder. Apparently it just won't work with the default 'mark as watched' context menu due to using the addDirectoryItem function.

**Comment by jkaw** [comment]
@MAR2196, the release should be out with a fix for this. 
Please let me know if this issue has been fixed for you, so I can close it.

**Comment by MAR2196** [comment]
Hey @jkaw, this issue has been fixed! I will be switching over to an integrated watchlist now. Thanks!
