### ISSUE TITLE
Anilist watchlist reversed and alldebrid cloudfiles

### ISSUE THREAD

**Issue by TaiDak** [Goldenfreddy0703/plugin.video.kaito.beta#32]
I just noticed that the watchlists for anilist are reversed, for example if you have set it up as "Last Updated" your last updated anime will show in Kodi at the end of the list.

Second thing is more of a request, if possible, to make it so that alldebrid cloudfiles can be scraped.

**Comment by jkaw** [comment]
I'll take a look at the anilist thing.

For alldebrid, I can try to see if seren has code for it and try to implement it.
However, I don't have an alldebrid account, so I wouldn't be able to test it.

**Comment by TaiDak** [comment]
It's all right, thank you for the work. I'll close this since the main issue, anilist is resolved
