### ISSUE TITLE
Other language support

### ISSUE THREAD

**Issue by jkaw** [Goldenfreddy0703/plugin.video.kaito.beta#36]
### Discussed in https://github.com/Goldenfreddy0703/plugin.video.kaito.beta/discussions/34

<div type='discussions-op-text'>

<sup>Originally posted by **pixelfenix** June  1, 2022</sup>
Hiya!

First of all thanks for taking over from Swag0Taku's great project! 
My girlfriend consumes french subtitled anime and currently the Nyaa scraper uses the following url which forces the results to be english only: https://nyaa.si/?f=0&c=1_2&q=%s&s=seeders&&o=desc

I have a local version of the old Kaito which uses https://nyaa.si/?f=0&c=1_0&q=%s&s=seeders&&o=desc instead which allows non english subtitles videos to come up as part of the results. Now obviously you don't want to do that for everyone because more often than not it will make the auto-select pick something that most users don't want but it's quite useful for me because it allows me to go select a french source from manual source select.

So if someone who is actually a programmer is able to add a "non english" feature that isn't on by default that would be amazing</div>

**Comment by jkaw** [comment]
@pixelfenix can you let me know if this has been solved for you?

**Comment by pixelfenix** [comment]
@jkaw I'll let you know as soon as I'm able to try it, if I install from Repo.hooty it should take the latest beta right?

**Comment by jkaw** [comment]
It should, yes. It will be beta 24. The setting will be the top setting under Sort/Filter in settings.
