### ISSUE TITLE
Myanimelist watchlist

### ISSUE THREAD

**Issue by thefatkid22** [Goldenfreddy0703/plugin.video.kaito.beta#38]
There was an error with updating the watchlist through MAL. Here is a pastebin with the error log. Pastebin.com/gwN54LbK  thanks.

**Comment by Goldenfreddy0703** [comment]
Hey thank you, we will take a look at it when we have the time.

**Comment by Goldenfreddy0703** [comment]
Hey @Gujal00 , I tried your pr but im still receiving an error with mal on my end but probably cause my mal is too messed up to use. 

Here is the error i got if you wanna take a look at that as well. 
![image](https://user-images.githubusercontent.com/62456796/184517551-3f9b2f01-ac0a-4488-9849-87e8d0435927.png)

**Comment by Gujal00** [comment]
Did you restart kodi after the update? The token refresh is part of service.py and us only run on kodi start @Goldenfreddy0703

**Comment by Goldenfreddy0703** [comment]
Hey @Gujal00 sorry i was busy but yes i did and did my troubleshooting steps as well

**Comment by Gujal00** [comment]
@Goldenfreddy0703 may be the differences between the old database format used in 0.10 and the beta.
Stop kodi, try deleting (or moving out) the database files (*.db and *.md5) in this folder and start kodi again
`profile\Kodi\userdata\addon_data\plugin.video.kaito`

**Comment by Gujal00** [comment]
Please test with #42

**Comment by Goldenfreddy0703** [comment]
ok, i will test it, give me a sec

**Comment by Goldenfreddy0703** [comment]
Hey so i just tried it and the Mal Watchlist Update sync fix worked, Thank you so much for fixing this

**Comment by Goldenfreddy0703** [comment]
Hey @thefatkid22 , im going to close this issue but if you still have any problems on this, feel free to comment and i will reopen this.

**Comment by thefatkid22** [comment]
Sounds good I try to test it tonight
