### ISSUE TITLE
Anilist Linking Issues

### ISSUE THREAD

**Issue by Guacan0le** [Goldenfreddy0703/plugin.video.kaito.beta#39]
I tried to link my Anilist by following the link I was given. I gave it the url and it said success, however my username doesn’t populate in the setting and shows as “Nones Anilist” in the addon menu.

**Comment by Goldenfreddy0703** [comment]
Hey there, have you tried my troubleshooting steps and did you also restart kodi to see if your username is there?

**Comment by Guacan0le** [comment]
It seems to be working now. I had to keep authorizing it until it finally showed up. I had restarted Kodi and tried all your troubleshooting steps.

**Comment by Goldenfreddy0703** [comment]
Nice, glad you got it working.
