### ISSUE TITLE
Limited providers despite having alldebrid and realdebrid accounts

### ISSUE THREAD

**Issue by jaimsitecom** [Goldenfreddy0703/plugin.video.kaito.beta#6]
![92250E2C-F7C6-4F63-A806-6A01724C0E46](https://user-images.githubusercontent.com/58242813/166888739-576f2381-8dfb-42ed-b4c7-ec78e04311cb.jpeg)

thanks for continuing this great addon. But am still having problems getting links to videos. Everytine i choose a video i want to watch it would go thru the searching of links as shown above. But very limited and few providers show up, only 3 actually show up namely NYAA, GOGO, CLOUD INSPECTION. Before i used to get several providers but since months ago, it stopped and these 3 only show up. Is there a setting i need to. Switch on/off? 

Hopefully this can still be fixed otherwised it’s really a dead addon for my part at least. 

Thanks in advance!

**Comment by jkaw** [comment]
Can you give examples of shows? 
It is possible you simply need to re-authenticate your debrid accounts.

**Comment by ahmedashed** [comment]
I think they are wondering why it is not scraping anything besides NYAA, GOGO and their cloud. I am not sure if that is part of the code of this addon to scrape any other sources?

**Comment by jkaw** [comment]
If that’s the case, I don’t believe this add on has ever had any options to scrape anything except for Nyaa, Gogo, and Cloud.

**Comment by jaimsitecom** [comment]
Any anime tv or movie wont scrape other than those 3 i showed above. I also revoked and re authenticated both alldebrid and realdebrid. I wonder why it stopped scraping from other providers (torrent and non-torrent). That’s sad. This was a great anime addon (now used to be). Sigh. 

Thanks anyways guys!
