### ISSUE TITLE
[BUG] Missing Watched Indicators

### ISSUE THREAD

**Issue by ahmedashed** [Goldenfreddy0703/plugin.video.kaito.beta#7]
Hey,

First of all, thank you very much for continuing this amazing work on a much needed anime debrid addon.

Bug report
It seems to be that watched indicators in my MAL list are only shown if I have watched the episode on my current machine/app. Where as in the previous Kaito version, if I have ticked that I watched it in my MAL, it will update as watched in Kodi. Essentially episodes aren't marked as watched on my MAL list section in Kaito despite it being watched on MAL. 

I have tried rebuilding the database, clearing local and torrent cache, reauthorising MAL list. I watched one episode in the TV show which did tick after finishing it but not the previous episodes. Basically this function is similar to getting watched indicators from Trakt, it used to work so I wonder why it stopped.

To Reproduce
Go to your MAL list in kaito
Select a TV show that you have watched a few episodes of (My case is HxH)
Once it loads you will find any episode that you haven't watched on your current Kodi/Machine will not have been ticked, despite marking it as watched on MAL. 

Screenshots
![image](https://user-images.githubusercontent.com/63984654/166903749-60a766e0-aa45-4e6e-adbb-415d38867427.png)
![image](https://user-images.githubusercontent.com/63984654/166903805-0c36bdf8-6dc4-4fea-8502-3ff21182b13c.png)

In these screenshots you will see that it detects I have watched 99 eps, but I only watched ep 99 on my current Kodi Machine. Hence the issue is why aren't the previous episodes marked. Thanks.

This might still be an issue with me but it definitely worked on the previous version.

System information
Nvidia Shield TV pro
Kodi 19.4 (Matrix)
Kaito 0.0.11.6 (latest update)

Thank you very much for all your hard work.

**Comment by jkaw** [comment]
This is a big one I’ve seen people mention. I am still working on general scraping improvements, but might take a look at this in a little bit.

**Comment by jkaw** [comment]
@ahmedashed I have committed a first entry in trying to fix your issue. 
I would do a rebuild database and clear cache after the update is installed.

Make sure that in Settings/Watchlist/General Update Watchlist is ticked and Watchlist to update is set to MAL.
After that you can click Manual Watchlist Update and check if a series you have marked in MAL as watched has it's episodes marked as watched.

**Comment by jkaw** [comment]
Some things to note:
the "Marked as watched" context menu is not going to work for updating watchlists. Consider it useless if you have a watchlist enabled. I'm going to see about adding a "Watchlist mark as watched" context menu to fix that.

If you watch an episode all the way through however, it will update your MAL (I believe this feature was already implemented by SwagOtaku).

Kitsu/Anilist not supported yet.

**Comment by joezito129** [comment]
Also version kaito 0.0.10 used to have what episode number that has been marked on mal.

for example it shows that I am on episode 8/25 on My Hero Academia on kaito 0.0.10.
![kaito_10](https://user-images.githubusercontent.com/60677138/168188746-e01c75bf-37f1-4a0d-a48f-15120f321660.PNG)

but kaito beta does not show any information on the episode number I am on.
![beta](https://user-images.githubusercontent.com/60677138/168188397-ec2b798d-e1c4-4248-9729-edae4eee2fb6.PNG)

**Comment by jkaw** [comment]
What view is that? MAL watchlist? Or in general?

**Comment by joezito129** [comment]
Mal watchlist

**Comment by ahmedashed** [comment]
> @ahmedashed I have committed a first entry in trying to fix your issue. I would do a rebuild database and clear cache after the update is installed.
> 
> Make sure that in Settings/Watchlist/General Update Watchlist is ticked and Watchlist to update is set to MAL. After that you can click Manual Watchlist Update and check if a series you have marked in MAL as watched has it's episodes marked as watched.

**Comment by ahmedashed** [comment]
> @ahmedashed I have committed a first entry in trying to fix your issue. I would do a rebuild database and clear cache after the update is installed.
> 
> Make sure that in Settings/Watchlist/General Update Watchlist is ticked and Watchlist to update is set to MAL. After that you can click Manual Watchlist Update and check if a series you have marked in MAL as watched has it's episodes marked as watched.

It has worked amazingly, I did not even need to rebuild my database or clear cache but definitely might be useful for others if they are not getting to work. Thank you very much for this!
![IMG20220513123831](https://user-images.githubusercontent.com/63984654/168275793-8b704164-7a03-425b-bf01-7d8c3b5dfd9c.jpg)

![IMG20220513123858](https://user-images.githubusercontent.com/63984654/168275819-f5590ee5-c24b-47ef-b877-c3384b40f175.jpg)

**Comment by ahmedashed** [comment]
> Also version kaito 0.0.10 used to have what episode number that has been marked on mal.
> 
> for example it shows that I am on episode 8/25 on My Hero Academia on kaito 0.0.10. ![kaito_10](https://user-images.githubusercontent.com/60677138/168188746-e01c75bf-37f1-4a0d-a48f-15120f321660.PNG)
> 
> but kaito beta does not show any information on the episode number I am on. ![beta](https://user-images.githubusercontent.com/60677138/168188397-ec2b798d-e1c4-4248-9729-edae4eee2fb6.PNG)

As you can see in my above pictures it does show the episode count when I set it up as a the widget in arctic horizon skin. So I think the issue is that you might need to play around with setting 'Set content types', maybe try Tvshows, episode etc.

**Comment by jkaw** [comment]
@joezito129 submit a new issue for your issue. It will get lost in here since the op closed this issue.
