### ISSUE TITLE
Not working at all

### ISSUE THREAD

**Issue by Hanbaga-sama** [Goldenfreddy0703/plugin.video.kaito.beta#8]
I installed the latest version of this beta but it NEVER works (except for Hunter x Hunter 2011, I dont know why), and Kodi gives me always an error ("One or more items failed to play. Check the log for more information about this message") even if I installed all the dependencies of any add-ons required by this version of Kaito. 

I tried on both my devices with Kodi 19.4 and python 3.8.9 in my Raspberry Pi 3 and Kodi 19.3 on my Android Phone.
Anybody have any ideas about how to fix this error? I'm starting to be crazy.

**Screenshot of this error =** ![photo1651754239](https://user-images.githubusercontent.com/104895062/166924370-cba6e1c1-7802-4da2-857f-1979247cdfba.jpeg)

**Kodi log files (Android) =** [kodi.log](https://github.com/Goldenfreddy0703/plugin.video.kaito.beta/files/8631338/kodi.log)

**Comment by Goldenfreddy0703** [comment]
Hey sorry i was having issues with my repo and alot of stuff happened, do you think you could redownload my repo again, update kaito, in the addon head to tools and clear cache, torrent cache, and rebuild database.

**Comment by Goldenfreddy0703** [comment]
You may want to also reconfigure your addon settings and authorize premiumize again.

**Comment by Goldenfreddy0703** [comment]
Hey btw, here is a tutorial to help you with this: https://github.com/Goldenfreddy0703/Otaku/issues/15

**Comment by jkaw** [comment]
Also something to add to the FAQ, this plugin won't work if you have Verizon as your ISP. Apparently they block nyaa entirely, so you have to load a vpn for it to work

**Comment by Hanbaga-sama** [comment]
Is Verizon an internet provider? No problem with that, I live in Italy ;)

**Comment by Goldenfreddy0703** [comment]
Oh yeah, it's also a mobile provider too.

**Comment by jkaw** [comment]
Can you do an addon settings wipe and try again? I’m not able to reproduce this at the moment. If it still doesn’t work, we’d probably need to add some more log statements to get more info

**Comment by Goldenfreddy0703** [comment]
Oh btw, did that tutorial help you and your problem out?

**Comment by Deadshot9669** [comment]
> Hey btw, here is a tutorial to help you with this: Goldenfreddy0703/Otaku#15

Oh thx a lot Goldenfreddy, but I have a question: are Premiumize/Real-debrid/Alldebrid services necessary for the proper work of this add-on? I currently do not have activated them on my devices, maybe thats the problem i was searching for.

**Comment by Goldenfreddy0703** [comment]
Oh well, this addon requires premium services like Premiumize, Real-debrid, or Alldebrid. Wiithout them, you would just be stuck with using Gogo anime and some of the sources don't work well.

**Comment by jkaw** [comment]
Oooh that would explain a lot @Hanbaga-sama. 

While the debrid services are not technically required, you will get much less sources if you don’t have them. 

This addon is aimed at people who want to watch anime in the highest possible quality (usually 1080p) so that’s why debrid services take priority. 

you can use other addons like nixtoons or gogo, as those don’t require debrid services. However the trade off will be lower quality streams.

**Comment by Hanbaga-sama** [comment]
You guys have got a nice point, apparently im quite dumb. But I dont have a premium account of those services (and I don't want it if it has a cost), I think i'm in a dead end again :(

**Comment by Goldenfreddy0703** [comment]
Real-Debrid is like 20$ for 6 months and that's a very good deal. If you want, you could try this alternative of kodi, i use to use it most of the time for my tv and it works like a charm. 
https://github.com/LagradOst/CloudStream-3

**Comment by Hanbaga-sama** [comment]
> Real-Debrid is like 20$ for 6 months and that's a very good deal. If you want, you could try this alternative of kodi, i use to use it most of the time for my tv and it works like a charm. https://github.com/LagradOst/CloudStream-3

Is this an add-on? Btw thx u a lot guys, you are the best <3

**Comment by Goldenfreddy0703** [comment]
Hey anytime and glad we could help.
